Create 0002-teorema-mestre-md
diogotcorreia/resumos-leic pull request #431
Opened 2021-12-02 16:30 UTC by Calhau18

2021-12-02 22:51 UTC, randomicecube commented
Still missing examples - waiting for the teacher's notes.

2021-12-03 09:43 UTC, randomicecube commented
This commit also needs the slides to be added (leaving this here so I don't forget to add them)

2021-12-04 17:44 UTC, diogotcorreia requested changes
I'll take care of this

2021-12-04 17:44 UTC, diogotcorreia commented on content/asa/0002-teorema-mestre.md
> +:::
Should be indented to be part of the bullet list

2021-12-04 17:44 UTC, diogotcorreia commented on content/asa/0002-teorema-mestre.md
> +É o **limite assimptótico inferior**, com notação $\Omega$ - afere a complexidade no melhor caso.
Should be indented to be part of the bullet list

2021-12-04 17:44 UTC, diogotcorreia commented on content/asa/0002-teorema-mestre.md
> +:::
Should be indented to be part of the bullet list

2021-12-04 17:44 UTC, diogotcorreia commented on content/asa/0002-teorema-mestre.md
> +Muitas vezes, uma abordagem que permite diminuir significativamente o tempo assimptótico em que é possível resolver um problema é usar uma abordagem de [**Dividir e conquistar**](color:orange).
```suggestion
Muitas vezes, uma abordagem que permite diminuir significativamente o tempo assimptótico em que é possível resolver um problema é usar uma abordagem de [**Dividir e Conquistar**](color:orange).
```

2021-12-04 17:44 UTC, diogotcorreia commented on content/asa/0002-teorema-mestre.md
> +![Dividir e Conquistar](./assets/0002-divide-conquer.png)
I'm pretty sure `C` and  `R` are accidentally swapped on this image

2021-12-04 17:44 UTC, diogotcorreia commented on content/asa/0002-teorema-mestre.md
> +\sum_{k=0}^{\log_b n} O \left( a^k (\frac{n}{b^k})^d \right) =
```suggestion
\sum_{k=0}^{\log_b n} O \left( a^k \left(\frac{n}{b^k}\right)^d \right) =
```

2021-12-04 17:44 UTC, diogotcorreia commented on content/asa/0002-teorema-mestre.md
> +T(n) = \textcolor{yellow}{2}\cdot T\left(\textcolor{orange}{\frac{n}{2}}\right) + O(n).
Colors on KaTeX have a problem that they're not dynamic, that is, they don't adapt to the light/dark theme of the website. I have a solution in mind for this, I'll fix it myself.

2021-12-04 17:44 UTC, diogotcorreia commented on content/asa/0002-teorema-mestre.md
> +right(i) = 2i + 1
```suggestion
\forall_{1 < i \leq n}, \quad A[\operatorname{parent}(i)] \geq A[i],
$$

com

$$
\operatorname{parent}(i) = \left\lfloor{\frac{i}{2}}\right\rfloor\\
\operatorname{left}(i) = 2i\\
\operatorname{right}(i) = 2i + 1
```

2021-12-04 17:50 UTC, Pesteves2002 commented
> I'll take care of this

"Fine, I'll do it myself"

2021-12-04 18:11 UTC, diogotcorreia approved these changes

2021-12-04 18:26 UTC, merged