[ASA] Add First Class notes (Missing slides and frontpage link)
diogotcorreia/resumos-leic pull request #432
Opened 2021-12-02 21:54 UTC by randomicecube

2021-12-02 22:01 UTC, randomicecube commented
The request was made so that adding the slides and the frontpage link wasn't forgotten

2021-12-02 22:54 UTC, diogotcorreia requested changes

2021-12-02 22:54 UTC, diogotcorreia commented on content/asa/0001-introducao.md
> +\forall_{n \geq 11} \text{ } fibo(n) \geq (\frac{3}{2})^n
```suggestion
\forall_{n \geq 11} \text{ } fibo(n) \geq \left(\frac{3}{2}\right)^n
```
Let the parenthesis match the height of the fraction

2021-12-02 22:54 UTC, diogotcorreia commented on content/asa/0001-introducao.md
> +O ramo de cima é igual ao da implementação anterior. O de baixo, contudo, é bastante diferente - não estamos dependentes de chamadas recursivas. Temos uma componente $c_1 * n$, correspondente às oper
```suggestion
O ramo de cima é igual ao da implementação anterior. O de baixo, contudo, é bastante diferente - não estamos dependentes de chamadas recursivas. Temos uma componente $c_1 \cdot n$, correspondente às operações realizadas durante o loop principal, e uma $c_2$ corrrespondente às outras operações da função, todas realizadas em tempo constante.
```

2021-12-02 23:08 UTC, diogotcorreia approved these changes

2021-12-03 14:08 UTC, diogotcorreia requested changes

2021-12-03 14:08 UTC, diogotcorreia commented on content/asa/0001-introducao.md
> +- [Notas da Aula - Prof. José Fragoso](https://web.tecnico.ulisboa.pt/jose.fragoso/asa/aula1.pdf)
Change this to a Google Drive mirror

2021-12-03 14:08 UTC, diogotcorreia commented on content/asa/0001-introducao.md
> +sum = \sum^{i - 1}_{k = 0}arr[k]
```suggestion
\operatorname{sum} = \sum^{i - 1}_{k = 0}\operatorname{arr} [k]
```

2021-12-04 17:02 UTC, diogotcorreia requested changes

2021-12-04 17:02 UTC, diogotcorreia commented on content/asa/exercicios/0001-fichas-2021-2022.md
> +  :::
The file path of these should be more specific, in order to allow to add more C++ solutions in the future.
I'll move them myself, don't worry.

2021-12-04 17:07 UTC, diogotcorreia approved these changes

2021-12-04 17:09 UTC, merged