[ASA] Add week 3 content
diogotcorreia/resumos-leic pull request #459
Opened 2021-12-21 13:12 UTC by randomicecube

2021-12-24 12:40 UTC, randomicecube commented
@diogotcorreia forgot to add the slides and teacher's notes - won't be able to add them right now, please don't merge the PR while I don't add them.

2021-12-25 23:32 UTC, diogotcorreia requested changes
Not very important changes. I think everything else is great, but I've only skimmed through it.
Feel free to merge it anyway, it's good enough for now and it can be improved later if needed.

2021-12-25 23:42 UTC, randomicecube commented on content/asa/0004-algoritmos-elementares.md
> +![DFS - Grafo do primeiro exemplo](./assets/0004-dfs-grafo-primeiro-exemplo.png#dark=1)
Alright, thanks!

2021-12-26 12:09 UTC, diogotcorreia requested changes

2021-12-26 12:09 UTC, diogotcorreia commented on content/asa/0004-algoritmos-elementares.md
> +| $f_i$ | 8   | 7   | 6   | 5   | 12  | 11  |
While doing the GIF, I noticed this is wrong. C is swapped with E.

2021-12-26 12:34 UTC, diogotcorreia approved these changes

2021-12-26 12:36 UTC, merged