[GES] Fix typos
diogotcorreia/resumos-leic pull request #466
Opened 2022-01-03 15:22 UTC by Pesteves2002

2022-01-03 22:38 UTC, diogotcorreia requested changes

2022-01-03 22:38 UTC, diogotcorreia commented on content/ges/0002-organizacoes-recursos-humanos.md
> +O IST preza-se pela sua excelência, pela formação teórica e prática de elevado nível dos seus alunos (**Elemento Invisíveis da Cultura**),
> Elemento Invisíveis

:thinking:

2022-01-03 22:38 UTC, diogotcorreia commented on content/ges/0002-organizacoes-recursos-humanos.md
> +a utilização do talento e capacidades das pessoas, de forma eficiente e eficaz, para atingir as metas da organização.\
```suggestion
a utilização do talento e capacidades das pessoas, de forma eficiente e eficaz, para atingir as metas da organização.  
```

Prefer double space over backslash for line break on markdown

2022-01-03 22:38 UTC, diogotcorreia commented on content/ges/0002-organizacoes-recursos-humanos.md
> +  Os sistemas de avaliação devem ser objetivos/claros, adaptados às mudanças das condições e dos requisitos para o exercicio de tarefas.\
```suggestion
  informação dos avaliados e aos gestores responsáveis na tomade de decisões com base nos desempenhos dos individuos.  
  Os sistemas de avaliação devem ser objetivos/claros, adaptados às mudanças das condições e dos requisitos para o exercicio de tarefas.  
```

Prefer double space over backslash for line break on markdown

2022-01-03 22:38 UTC, diogotcorreia commented on content/ges/0003-ambiente-economico.md
> +Como o próprio nome indica a **Macroeconomia** retrata o grande cenário - o Estado, a Economia Nacional
```suggestion
Como o próprio nome indica, a **Macroeconomia** retrata o grande cenário - o Estado, a Economia Nacional
```

2022-01-03 22:38 UTC, diogotcorreia commented on content/ges/0003-ambiente-economico.md
> +- **Taxa de Inflação**: Taxa de variação de preços medido pelo indíce de preços do consumidor (IPC).
```suggestion
- **Taxa de Inflação**: Taxa de variação de preços medido pelo índice de preços do consumidor (IPC).
```

2022-01-03 22:38 UTC, diogotcorreia commented on content/ges/0003-ambiente-economico.md
> +A **Deflação** é o processo inverso à inflação, ou seja, uma diminuição do indíce de preços do consumidor, associada a uma queda de preços.
```suggestion
A **Deflação** é o processo inverso à inflação, ou seja, uma diminuição do índice de preços do consumidor, associada a uma queda de preços.
```

2022-01-03 22:38 UTC, diogotcorreia commented on content/ges/0004-informacao-financeira.md
> +O capital próprio traduz o valor contabilístico da empresa num determinado momento:\
```suggestion
O capital próprio traduz o valor contabilístico da empresa num determinado momento:  
```
Prefer double space over backslash for line break on markdown

2022-01-03 22:38 UTC, diogotcorreia commented on content/ges/0004-informacao-financeira.md
> +Balança do Resultados:
```suggestion
Balança dos Resultados:
```

2022-01-04 00:10 UTC, Pesteves2002 reviewed
NOW

2022-01-04 00:14 UTC, diogotcorreia approved these changes

2022-01-04 00:15 UTC, merged