[ASA] Add week 4 content
diogotcorreia/resumos-leic pull request #467
Opened 2022-01-03 23:42 UTC by randomicecube

2022-01-06 23:05 UTC, randomicecube commented
@diogotcorreia I think this is ready for review, missing teacher's notes (they aren't available atm) which can be added whenever they're made available

2022-01-09 13:00 UTC, diogotcorreia requested changes

2022-01-09 13:00 UTC, diogotcorreia commented on content/asa/0005-caminhos-mais-curtos.md
> +    d[v] := +\infty
```suggestion
    d[v] := +infinity
```

2022-01-09 13:00 UTC, diogotcorreia commented on content/asa/0005-caminhos-mais-curtos.md
> +InitializeSingleSource(G, s) // ocorre em \Theta(|V|) tempo
```suggestion
InitializeSingleSource(G, s) // ocorre em Theta(|V|) tempo
```

2022-01-09 13:00 UTC, diogotcorreia commented on content/asa/0005-caminhos-mais-curtos.md
> +Relax(G, u, v, w) // ocorre em \Theta(1) tempo
```suggestion
Relax(G, u, v, w) // ocorre em Theta(1) tempo
```

2022-01-09 13:00 UTC, diogotcorreia commented on content/asa/0005-caminhos-mais-curtos.md
> +    for each v in Adj[u] do // \Theta(E) vezes durante o algoritmo
```suggestion
  InitializeSingleSource(G, s) // ocorre em Theta(V) tempo
  let S := new array
  let Q := new queue(V)
  while Q is not empty do // ocorre Theta(V) vezes
    let u := extractMin(Q) // V vezes * O(logV) durante o algoritmo
    S.add(u)
    for each v in Adj[u] do // Theta(E) vezes durante o algoritmo
```

2022-01-09 21:06 UTC, diogotcorreia approved these changes

2022-01-09 21:06 UTC, merged