[SO] Improve content and add interesting facts
diogotcorreia/resumos-leic pull request #577
Opened 2022-02-22 12:22 UTC by Pesteves2002

2022-02-22 12:25 UTC, Pesteves2002 commented
@abread LGTY?

2022-02-24 18:53 UTC, abread requested changes

2022-02-24 18:53 UTC, abread commented on content/so/0008-sistemas.md
> +Nos computadores pessoais é habitual este programa ser uma implementação do **BIOS** (_Basic Input/Output System_) ou da **UEFI** (_Unified Extensible Firmware Interface_).
Género é um bocado estranho aqui, diria "implementação d**e** BIOS (...) ou UEFI"

2022-02-24 18:53 UTC, abread commented on content/so/0009-process-management.md
> +Fechar e abrir mutex's são chamadas de sistema. O núcleo mantém o estado de cada trinco, bem como uma lista de tarefas bloqueadas por esse trinco. A espera bloqueante é conseguida com ajuda do núcleo
O meu ponto aqui era não mencionar específicos do que é que o núcleo mantém ou deixa de manter, ou seja, tirar a frase que diz que mantém o estado de cada trinco e lista de tarefas bloqueadas. Pode não ser verdade noutros sistemas, e **não é** totalmente verdade em Linux, que mantém só conjuntos de tarefas bloqueadas em *futexes* (que são mais parecidos a `pthread_cond_t`s que trincos)

2022-02-24 21:21 UTC, merged